### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ratelimit_method'

### ISSUE THREAD

**Issue by dblicken** [halcy/MastodonToTwitter#5] opened 2016-11-29 02:26 UTC
Greetings,

All of the install/authentication pieces seem to be working for me but the script fails with this error. Any help you have would be much appreciated.

$ Python3 MastodonToTwitter.py 
Traceback (most recent call last):
  File "MastodonToTwitter.py", line 173, in <module>
    api_base_url = MASTODON_BASE_URL
TypeError: __init__() got an unexpected keyword argument 'ratelimit_method'

**Comment by halcy** [comment] 2016-11-29 08:35
Hi,

are you on the newest Version of Mastodon.py? The ratelimiting code is new.

I should write a requirements.txt to automate  dependency installation probably...

**Comment by dblicken** [comment] 2016-11-29 16:24
Thanks! I don't think I was on the very latest. So, I ran $ pip3 install --upgrade --force-reinstall  Mastodon.py python-twitter. Now, MastodonToTwitter.py appears to run without errors but does not take any interactive input and appears hung.

$ Python3 MastodonToTwitter.py

[EDIT: Possibly hanging here?]

$ Python3 MastodonToTwitter.py
^CTraceback (most recent call last):
  File "MastodonToTwitter.py", line 283, in <module>
    time.sleep(MASTODON_POLL_DELAY)

**Comment by halcy** [comment] 2016-11-29 16:34
This is expected behaviour, assuming you already logged in successfully. Did you try making a post on Mastodon? It should appear on twitter

**Comment by dblicken** [comment] 2016-11-29 17:11
Resolved! Thanks!

**Comment by halcy** [comment] 2016-11-29 17:12
I'd like to keep this open to remind me to add a requirements.txt as well as a small message when starting up with login that things are working as intended. I will close it once that is done.

**Comment by dblicken** [comment] 2016-11-29 17:13
Sure thing! Thanks again---

**Closed as completed** 2016-12-13 13:41 UTC
